roles: []
replicas: 1
minimumMasterNodes: 0

extraEnvs:
  - name: discovery.type
    value: single-node
  - name: node.roles
    value: master,data,data_content,data_hot,data_warm,data_cold,ingest,ml,remote_cluster_client,transform

esJavaOpts: "-Xmx1024m -Xms1024m"

resources:
  requests:
    cpu: "0m"
    memory: "0Gi"
  limits:
    cpu: "1000m"
    memory: "4Gi"
antiAffinity: "soft"

